### ISSUE TITLE
gap_cover() fails when using by_line = TRUE

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#103]
When spreading the object `gap_summary` into its three wide data frames while `by_line = TRUE`, `tidyr::spread()` throws the following error:
```Error in `tidyr::spread()`:
! Each row of output must be identified by a unique combination of keys.```

**Comment by nstauffer** [comment]
Proposed patch changes the `gap_summary` variable selection step so that when `by_line = TRUE`, `LineKey` is included as a variable to keep.

```
  # Subset the fields we need to output
  if (by_line) {
    gap_summary <- gap_summary %>%
      dplyr::select(PrimaryKey, LineKey, total_line_length, interval, n, length, percent)
  } else {
    gap_summary <- gap_summary %>%
      dplyr::select(PrimaryKey, total_line_length, interval, n, length, percent)
  }
```

**Comment by josephbrehm** [comment]
resolved on joe-dev
