### ISSUE TITLE
soil_stability() returns NA results when any included stability ratings are NA

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#113]
There are some data sets (like the soil stability data for ecosite R036XB006NM currently in the LDC) that include NA values in the soil stability rating variable. It looks like any stability calculation that includes an NA produces a result of NA. Consider adding at least a warning to the end user as to why there are NA values being produced. If appropriate, maybe just exclude the NA values and warn the user that that's happened?

**Comment by josephbrehm** [comment]
resolved on joe-dev

**Comment by smccord** [comment]
Thanks Joe! We need to let Nathan know (I can do that). This is definitely our impetus to do a new release for BLM this fall (and possible recalc a few things).
