### ISSUE TITLE
Allow gather_species() to accept data frames in addition to CSVs

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#116]
Currently, `gather_species()` takes a filepath as the input `species_file`, but it'd be extremely helpful if that argument could also be a data frame that's already in the working environment. I think that it'd be relatively simple to have it check if `class(species_file) %in% c("character")` and only attempt to read in data if it's a filepath string and not a data frame.

This is actually true of any functions that take filepaths to data. Since I'm frequently manipulating/cleaning data before feeding it to terradactyl functions, being able to pass in my data frames and not have to write to CSV first would be really helpful!

**Comment by smccord** [comment]
Makes sense, Joe are you able to add this to the to do list?

**Comment by josephbrehm** [comment]
Yes, definitely. Would you like me to put this in with the current batch of updates? My inclination is yes.

**Comment by nstauffer** [comment]
Well, it appears that this is actually already the case and I misread the documentation. So no need to tackle this, mea culpa.
