### ISSUE TITLE
IIRH Code Review

### ISSUE THREAD

**Issue by smccord** [Landscape-Data-Commons/terradactyl#12]
@nstauffer @cedillon, when you get a chance, could you review the [IIRH ](https://github.com/smccord/terradactyl/blob/master/R/IIRH.R ) functions in terradactyl? Thanks!

**Comment by nstauffer** [comment]
In the gather functions I'm not sure about the arguments because we might not want to force the filename of the .txt file.

What about:
```
function(dsn){
  file.type <- tolower(stringr::str_extract(dsn, pattern = "[A-z]{3}$"))
  if (!grepl(file.type, pattern = "^(gdb)|(txt)$", ignore.case = TRUE)) {
    stop("Invalid file extension. dsn must point to either a .gdb or .txt file")
  }
  if (!file.exists(dsn)) {
    stop(paste("Unable to find the file", dsn))
  }

  # Read in the data as .txt or .gdb
  IIRH <- switch(file.type,
    "gdb" = {
      suppressWarnings(sf::st_read(dsn,
        layer = "RANGEHEALTH",
        stringsAsFactors = FALSE
      ))
    },
    "txt" = {
      read.table(dsn),
        stringsAsFactors = FALSE,
        header = FALSE,
        sep = "|",
        strip.white = TRUE
      )
    }

....
}
```

**Comment by smccord** [comment]
I actually feel pretty strongly about that one in this case. The only case
we'd be reading a .txt file for LMF/NRI is if it comes straight from ISU,
and that's their file format. Always. If we hard code the file name it
keeps this under control and we force and error if it's not the case. Down
the road we can always build a more flexible txt file gather function for
other types. But let me know if I'm missing something here.

**Comment by nstauffer** [comment]
That makes perfect sense to me!

**Comment by smccord** [comment]
Done
