### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by smccord** [Landscape-Data-Commons/terradactyl#132]
1) Point to terradactyl manuscript
2) use remotes::install_github("https://github.com/Landscape-Data-Commons/terradactyl") instead of devtools (remotes is part of base R installations)

**Comment by nstauffer** [comment]
Use the remotes package instead of devtools.

**Comment by nstauffer** [comment]
- Updated installation code snippet
- Added the McCord et al. 2022 reference to the initial overview
- Added McCord et al. 2022 to the works cited
- Corrected link to the Monitoring Manual in the works cited
