### ISSUE TITLE
Standardize grouping variable handling in low-level functions

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#163]
For functions like `gap_cover()` and `pct_cover()`, grouping variables are handled differently but conceptually it makes sense for them to be handled the same way.

`gap_cover()` has a the argument `by_line` which lets the user toggle whether the output is calculated using PrimaryKey or PrimaryKey and LineKey to group the data.

`pct_cover()` has the same behavior tied to an argument also called `by_line`. It also has the ability to accept any number of additional grouping variables as unnamed arguments.

They can be left as-is, but we should consider changing the grouping variable handling to be done with a single argument that takes a vector of variable names and defaults to `c("PrimaryKey")`. The `by_line` argument could be left in place and simply enforce the inclusion of `"LineKey"` in the vector as a way to maintain more backwards compatibility. This would also resolve the issue of needing to specify values for all named arguments even when the intent is to use the default value for an argument.

**Comment by nstauffer** [comment]
I realized that "grouping variable" means two different things. One is for grouping data together and one is for the variables that define the indicators. This can probably be disregarded.

**Comment by smccord** [comment]
I agree we should leave as is. by_line specifies the analysis unit. The
grouping variables define the response variables
