### ISSUE TITLE
gather_species() fails with .csv

### ISSUE THREAD

**Issue by aspidoscelis** [Landscape-Data-Commons/terradactyl#31]
When using `gather_species()` on a .csv file, it appears that the `na.strings = c("", " ")` argument in `read.csv()` (line 39 of species.R) results in the replacement of `""` and `" "` with the character string `"NA"`. This, then, means that `species_join()` (at lines 253-266 of species.R) will replace your plant codes with the character string `"NA"`!

This seems like an extremely unhelpful thing for `na.strings` to do, and pretty much the opposite of what you'd expect, but it's working the same way on my desktop RStudio (1.2.5019 under macOS 10.12.6) and in RStudio Cloud, including after restarting RStudio and only loading the libraries listed in install.R.

Without that argument, missing values are correctly interpreted as the logical constant `<NA>` and both `gather_species()` and `species_join()` work fine.

**Comment by smccord** [comment]
Can you send me the species list you're working with? I'm not seeing why that would be happening.

**Comment by aspidoscelis** [comment]
Oh no. Now I need to remember what I was doing. :-)

**Comment by aspidoscelis** [comment]
OK, I've attached a file and a screenshot... 'tblStateSpecies_NM.csv' (in the zip-it won't let me just upload the csv) is just the tblStateSpecies from the NOC SQL server filtered to New Mexico and output as csv. If I do the following:
`tblStateSpecies_NM <- read_csv("tblStateSpecies_NM.csv")`
`gather_species_tblStateSpecies_NM <- gather_species("tblStateSpecies_NM.csv")`

I get:

![tblStateSpecies_NM](https://user-images.githubusercontent.com/35407546/72292187-1c45cd00-360e-11ea-8c1b-4eecfd411851.png)

And:

![gather_species_tblStateSpecies_NM](https://user-images.githubusercontent.com/35407546/72292198-223bae00-360e-11ea-9e44-d27b0c57c1d3.png)



[tblStateSpecies_NM.zip](https://github.com/smccord/terradactyl/files/4055728/tblStateSpecies_NM.zip)
