### ISSUE TITLE
mean_height() drops grouping variables when method = "max"

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#50]
It looks like there's code that's preventing max heights from being calculated because it overwrites height_tall with a summary data frame which does not have the grouping variable(s) in it. It's the first function call in `if (method = "max") {}`
I think that it doesn't quite work correctly without it, summarizing grouped only by primarykey and whatever grouping variables.

Offending code:
`height_tall <- height_tall %>% dplyr::group_by(PrimaryKey, 
      LineKey, PointNbr) %>% dplyr::summarise(max = max(Height))`

**Comment by nstauffer** [comment]
I know it's a bit late in the game, but it may make sense to break mean and max height calculations into separate functions that're called by a more appropriately named main function.

**Comment by smccord** [comment]
This is a feature not a bug. We're looking at the average maximum height recorded at each pin drop. We'll update the help documentation
