### ISSUE TITLE
Some function calls are missing explicit namespaces

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#7]
The only one I've hit so far is vars() in pct.cover(), but if it's anything like the code I write I bet there are other places where the namespace is unspecified and the package isn't attached automatically.

**Comment by smccord** [comment]
Yep! I caught a bunch today—and still haven’t pushed. Loading tidyverse
should tide you over. There’s gotta be. A package somewhere that checks
that....

**Comment by nstauffer** [comment]
That was my solution. I hadn't yet just because that's my habit with my own packages to catch this stuff.

Maybe lintr:: checks that?
