### ISSUE TITLE
Function to get user-customized species code lists from species inventory tall file

### ISSUE THREAD

**Issue by annack84** [Landscape-Data-Commons/terradactyl#76]
It would be nice for non-AIM package users to be able to generate outputs that match those of spp_inventory_calc() for species attributes other than just Noxious/NonNoxious. Right now, species_count() gets you the number of species for a custom species attribute, but there's no function within the terradactyl package to get the list of species codes (like columns "Spp_NonNox" and "Spp_Nox") for a custom species attribute (at least, not that I can find). It looks like turning lines 1078-1098 of spp_inventory_calc() into a function that accepts any column name from the species list should do the trick.

**Comment by smccord** [comment]
Great idea. We'll put it on the list.
