### ISSUE TITLE
Calculate line lengths for LMF for canopy gap instead of hardcoding

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#90]
In gather_gap_lmf() the line length should be calculated instead of assumed. This is because LMF may not measure the full length of two transects. Each transect can be broken into up to three segments and each segment may receive a different designation, some of them unmeasured, i.e., any segment with an XI, XR, XN, or XW designation will not be measured and should not be included in the calculation. See LMF Handbook 2022 section 8.6.2 for details

Proposed solution:
For each PRIMARYKEY value in the table ESFSG, find the sum of line lengths of segments with ESFSG_STATE values that are not equal to XI, XR, XN, or XW, converting from imperial to metric (METERS!) and storing that as the LineLengthAmount value instead of hardcoding an assumed value. If COVERAGE is "all" then assume a line length of 150 feet.

This might require calculating the total sampled line length and dividing by two to fake a constant line length. Double check the behavior regarding treatment of LineLengthAmount to make sure about that!

**Comment by nstauffer** [comment]
This requires review and testing still!

Apologies, but I couldn't tie the branch to this issue, so I already opened a pull request in order to associate that. The branch is named lmf_line_length.

**Comment by nstauffer** [comment]
Testing has turned up 46 plots from the 2020 data where gap start or end values fell within a part of a transect designated as XI, XR, XN, or XW. One of these plots exceeds 100% gap due to this issue (one transect was designated as XR for all 150 feet but gaps were measured along the transect).

We need to confirm how gap works relative to the segment designations. The handbook says:

> Ineligible cover types may intersect the transect lines. If this occurs, use the coverage feature to disqualify portions of the transect from certain data collection protocols.

We can't find anywhere in the handbook that specifies which data collection protocols however. The small number of plots where gaps were measured in/into the X* segments suggests that those may be either errors or there may be some leeway in the protocol. In the latter case, it's not clear how to calculate appropriate line lengths.

There is also one plot where all 150 feet of a transect was designated XR (road) but gaps were recorded. There is no associated line length however, and so joining the lookup table to the gap data results in NA values in the LineLengthAmount variable for those records. Should we set up default handling for those scenarios?

**Comment by smccord** [comment]
Todd and I have this flagged (among other issues) to sort out. So we should
check in with ISU for their recommendation.
