### ISSUE TITLE
LMF2021 Data Schema Change, Addition of ESFSG_PREFIX Field, Needs to be incorporated in EcolSite 

### ISSUE THREAD

**Issue by srm12014** [Landscape-Data-Commons/terradactyl#98]
LMF2021 data is adding a new field, ESFSG_PREFIX, to designate if an LMF plot is on rangeland (R) or forest (F); sites with ineligible cover types (XE, XI, XN, XW, XR, etc., reference section 8.6.2 of the LMF Handbook for more detail) result in a blank for that field. This new information needs to be incorporated in EcolSite, so I propose that this be updated in gather_plot_characterization.R , line 167 where we build the EcolSite, but totally open to other options if Sarah or Joe have a better fix in mind. I don't know if the ESFSG_PREFIX actually needs to be the EcolSite prefix, but I've put it at the front of the concatenation queue in my example fix. 

#get ecological site and mlra from ESFSG
 
  esfsg_lmf <- esfsg_lmf_raw %>% dplyr::mutate(
     
    EcolSite = paste0(**ESFSG_PREFIX**, ESFSG_MLRA, ESFSG_SITE, ESFSG_STATE ) %>% ecosite_qc(),
       
    MLRA = ESFSG_MLRA %>% gsub("^$", NA, .)
  ) %>% dplyr::select(   
    PrimaryKey, DBKey,
    EcolSite, MLRA    )
                )

**Comment by smccord** [comment]
@srm12014 Sounds good, I think we can do this. 
@josephbrehm We'll need to add an if statement so that we don't get an error when we run old data. Also, it sounds like we'll need to add a trimws() after so that we drop any blanks.

**Comment by srm12014** [comment]
An additional important note that @smccord mentioned yesterday: We should probably override ecosite_qc with the new ESFSG_Prefix field, so that it doesn't automatically put an R prefix where there should not be one.

**Comment by srm12014** [comment]
For sites that don't have an R/F designation, what do we put as the prefix? An automatic R or 0 or something else?
